name: actions
on: [push, pull_request]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install WASM Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Install WASM Binding Generator
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-bindgen-cli
          version: 0.2.74
          # use-tool-cache: true
      - name: Compile Native
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --examples
      - name: Compile WASM
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: --cfg=web_sys_unstable_apis
        with:
          command: build
          args: --release --examples --target wasm32-unknown-unknown
      - name: Generate WASM Binding
        run: wasm-bindgen --out-dir target/wasm --web target/wasm32-unknown-unknown/release/examples/showcase.wasm
      - uses: actions/upload-artifact@v2
        with:
          path: |
            target/wasm/
            target/release/examples/